apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  schema.sql: |
    use task_db

    CREATE TABLE tasks (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );