apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: php-task-app-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-task-app-app
  template:
    metadata:
      labels:
        app: php-task-app-app
    spec:
      containers:
      - name: app
        image: manteq/php-task-app-app:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-volume
          mountPath: /var/www/html
      volumes:
      - name: app-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: php-task-app-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer