name: CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/php-task-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/php-task-app:latest

      # Deploy locally
      # - name: Deploy locally
      #   run: |
      #     docker pull ${{ secrets.DOCKER_USERNAME }}/php-task-app:latest
      #     docker stop php-task-app || true
      #     docker rm php-task-app || true
      #     docker run -d --name php-task-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/php-task-app:latest
