name: CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/php-task-app-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/php-task-app-app:latest

      # Deploy locally
      # - name: Deploy locally
      #   run: |
      #     docker pull ${{ secrets.DOCKER_USERNAME }}/php-task-app-app:latest
      #     docker stop php-task-app || true
      #     docker rm php-task-app || true
      #     docker run -d --name php-task-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/php-task-app-app:latest


  send-mail:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Send notification email
        run : |
          echo "Envoi d'un mail en cas de succès de la CD"

      # uses: dawidd6/action-send-mail@v3
      # with:
      #   server_address: smtp.gmail.com
      #   server_port: 587
      #   username: ${{ secrets.MAIL_USERNAME }}
      #   password: ${{ secrets.MAIL_PASSWORD }}
      #   subject: CD - OK !
      #   body: |
      #     Le test CD est OK !
      #   to: jminchin.sio@gmail.com
      #   from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
