name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: task_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Verify application
      - name: Verify application
        run: |
          php -S localhost:8000 -t src &
          sleep 5
          curl -f http://localhost:8000/index.php

  set-php:
    needs: build
    runs-on: ubuntu-latest

    steps: 
      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_mysql

      # Install Composer
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install

      # Run PHP linting
      - name: Run PHP lint
        run: |
          find src -name "*.php" -exec php -l {} \;


  set-database:
  needs: [build]
  runs-on: ubuntu-latest

  steps:
    # Run database migrations
    - name: Set up database schema
      run: |
        mysql -h 127.0.0.1 -u root -proot task_db < database/schema.sql


  # exec-tests:
  # needs: [set-php, set-database]
  # runs-on: ubuntu-latest

  # steps:
  #   # Run tests (if applicable)
  #   - name: Run tests
  #     run: |
  #       # vendor/bin/phpunit ./src/tests/test-db.php